name : first

on: [push]

jobs:
    job1:
        name: first job
        runs-on: ubuntu-latest
        steps:
        - name: step1
          uses: actions/checkout@v2
        - name: step2
          run: env | sort
    job2:
        name: second job
        runs-on: windows-latest
        steps:
        - name: step1
          uses: actions/checkout@v2
        - name: step2
          run: "Get-ChlidItem Env: | Sort-Object Name"
